#!/usr/bin/env bash
NAMESPACE=${1}
RED_HAT_CONTAINER_IMAGE=registry.access.redhat.com/ubi8/openjdk-8:1.3
OPENJDK_APP_IMAGESTREAM_NAME=ubi8-openjdk8
IBM_SEMERU_CONTAINER_IMAGE=icr.io/appcafe/ibm-semeru-runtimes:open-8-jdk-ubi-minimal
OPENJ9_APP_IMAGESTREAM_NAME=semeru-openj9-jdk8-rhel8

oc new-app -f .openshiftio/openjdk-to-openj9-transition.yaml -p RED_HAT_CONTAINER_IMAGE=$RED_HAT_CONTAINER_IMAGE -p OPENJDK_APP_IMAGESTREAM_NAME=$OPENJDK_APP_IMAGESTREAM_NAME -p IBM_SEMERU_CONTAINER_IMAGE=$IBM_SEMERU_CONTAINER_IMAGE -p OPENJ9_APP_IMAGESTREAM_NAME=$OPENJ9_APP_IMAGESTREAM_NAME -p NAMESPACE=$NAMESPACE

